### ISSUE TITLE
Pls update to Velocity 1.0.0 release

### ISSUE THREAD

**Issue by LarsArtmann** [xElementzx/VelocityUuidGetter#1]
http://prntscr.com/o52uvw

**Comment by xElementzx** [comment]
https://github.com/xElementzx/VelocityUuidGetter/releases/tag/V1.0.1

Try this version and report back, it seems that in my environment a recompile with the latest version of the velocity api has resolved the issue.

**Comment by LarsArtmann** [comment]
Thx, it works 👍
